export default {
  "login": "kunal-kushwaha",
  "id": 42698533,
  "node_id": "MDQ6VXNlcjQyNjk4NTMz",
  "avatar_url": "https://avatars.githubusercontent.com/u/42698533?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kunal-kushwaha",
  "html_url": "https://github.com/kunal-kushwaha",
  "followers_url": "https://api.github.com/users/kunal-kushwaha/followers",
  "following_url": "https://api.github.com/users/kunal-kushwaha/following{/other_user}",
  "gists_url": "https://api.github.com/users/kunal-kushwaha/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kunal-kushwaha/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kunal-kushwaha/subscriptions",
  "organizations_url": "https://api.github.com/users/kunal-kushwaha/orgs",
  "repos_url": "https://api.github.com/users/kunal-kushwaha/repos",
  "events_url": "https://api.github.com/users/kunal-kushwaha/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kunal-kushwaha/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Kunal Kushwaha",
  "company": "Civo",
  "blog": "https://kunalkushwaha.com",
  "location": "London, UK",
  "email": null,
  "hireable": null,
  "bio": "Empowering communities via open-source and education.",
  "twitter_username": "kunalstwt",
  "public_repos": 159,
  "public_gists": 1,
  "followers": 20195,
  "following": 0,
  "created_at": "2018-08-25T15:01:59Z",
  "updated_at": "2023-02-21T00:10:37Z"
  }
