export default {
  "login": "hkirat",
  "id": 8079861,
  "node_id": "MDQ6VXNlcjgwNzk4NjE=",
  "avatar_url": "https://avatars.githubusercontent.com/u/8079861?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/hkirat",
  "html_url": "https://github.com/hkirat",
  "followers_url": "https://api.github.com/users/hkirat/followers",
  "following_url": "https://api.github.com/users/hkirat/following{/other_user}",
  "gists_url": "https://api.github.com/users/hkirat/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/hkirat/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/hkirat/subscriptions",
  "organizations_url": "https://api.github.com/users/hkirat/orgs",
  "repos_url": "https://api.github.com/users/hkirat/repos",
  "events_url": "https://api.github.com/users/hkirat/events{/privacy}",
  "received_events_url": "https://api.github.com/users/hkirat/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Kirat",
  "company": null,
  "blog": "",
  "location": "Earth",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 80,
  "public_gists": 5,
  "followers": 7203,
  "following": 99,
  "created_at": "2014-07-06T09:05:37Z",
  "updated_at": "2023-08-31T22:11:18Z"



}